model:
  base_learning_rate: 4.5e-6
  target: taming.models.vqgan.VQModel
  params:
    embed_dim: 256
    n_embed: 1024    ### 원래 1024
    ddconfig:
      double_z: False
      z_channels: 256        # 보통 z_channels랑 embed_dim랑 같게 하는 듯. encode시 z_channels dim을 embed_dim로 바꿔주는 1x1conv가 있음
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,1,2,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0

    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 30001
        disc_weight: 0.8
        codebook_weight: 1.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 8    ### 원래 3
    num_workers: 8   ### 원래 8
    train:
      target: taming.data.mimiccxr.MimicCXRTrain
      params:
        size: 256
        crop_size: 256
    validation:
      target: taming.data.mimiccxr.MimicCXRValidation
      params:
        size: 256
        crop_size: 256
