name: negbio2.7
channels:
  - anaconda
  - conda-forge
  - auto
dependencies:
  - python=2.7.11
  - future=0.16.0
  - docutils=0.13.1
  - docopt=0.6.2
  - pytest=3.1.3
  - networkx=1.11
  - ply=3.10
  - tqdm=4.19.5
  - nltk=3.2.4
  - pathlib2=2.3.3
  - numpy=1.15.4
  - jpype1=0.6.3
  - pip:
    - bioc==1.1.dev3
    - pystanforddependencies==0.3.1
    - bllipparser==2016.9.11
    - pymetamap==0.1
